-- Migration: Fix NCERT Unique Constraint & Reseed Class 6-12 Comprehensive Textbooks
-- Also add Doubt Resolution columns to Community posts & comments

-- 1. DROP the old flawed constraint that caused: Key (class_number, subject, chapter_number)=(9, Social Science, 1) already exists.
ALTER TABLE public.ncert_books DROP CONSTRAINT IF EXISTS ncert_books_unique_chapter;
DROP INDEX IF EXISTS public.ncert_books_unique_chapter;

-- 2. CREATE the correct unique index including book_name so different books under the same subject can each have Chapter 1
CREATE UNIQUE INDEX IF NOT EXISTS ncert_books_unique_chapter_v2
  ON public.ncert_books (class_number, subject, book_name, chapter_number);

-- 3. Add Community Doubt Resolution Columns
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS doubt_subject text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS doubt_class text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS doubt_status text DEFAULT 'unsolved'; -- 'unsolved' | 'solved'
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS accepted_comment_id uuid;

ALTER TABLE public.post_comments ADD COLUMN IF NOT EXISTS is_accepted_solution boolean NOT NULL DEFAULT false;

-- 4. CLEAN OLD NCERT DATA AND RESEED ALL VERIFIED CHAPTERS FOR CLASSES 6 TO 12
DELETE FROM public.ncert_books;

INSERT INTO public.ncert_books (class_number, subject, book_name, chapter_title, chapter_number, file_url) VALUES
-- =================== CLASS 6 ===================
('6', 'Mathematics', 'Ganita Prakash – Class 6', 'Chapter 1 – Patterns in Mathematics', 1, 'https://ncert.nic.in/textbook/pdf/femh101.pdf'),
('6', 'Mathematics', 'Ganita Prakash – Class 6', 'Chapter 2 – Lines and Angles', 2, 'https://ncert.nic.in/textbook/pdf/femh102.pdf'),
('6', 'Mathematics', 'Ganita Prakash – Class 6', 'Chapter 3 – Number Play', 3, 'https://ncert.nic.in/textbook/pdf/femh103.pdf'),
('6', 'Mathematics', 'Ganita Prakash – Class 6', 'Chapter 4 – Data Handling and Presentation', 4, 'https://ncert.nic.in/textbook/pdf/femh104.pdf'),
('6', 'Mathematics', 'Ganita Prakash – Class 6', 'Chapter 5 – Prime Time', 5, 'https://ncert.nic.in/textbook/pdf/femh105.pdf'),
('6', 'Mathematics', 'Ganita Prakash – Class 6', 'Chapter 6 – Perimeter and Area', 6, 'https://ncert.nic.in/textbook/pdf/femh106.pdf'),
('6', 'Science', 'Curiosity – Class 6', 'Chapter 1 – The Wonderful World of Science', 1, 'https://ncert.nic.in/textbook/pdf/fesc101.pdf'),
('6', 'Science', 'Curiosity – Class 6', 'Chapter 2 – Diversity in the Living World', 2, 'https://ncert.nic.in/textbook/pdf/fesc102.pdf'),
('6', 'Science', 'Curiosity – Class 6', 'Chapter 3 – Mindful Eating: A Path to a Healthy Body', 3, 'https://ncert.nic.in/textbook/pdf/fesc103.pdf'),
('6', 'Science', 'Curiosity – Class 6', 'Chapter 4 – Exploring Magnets', 4, 'https://ncert.nic.in/textbook/pdf/fesc104.pdf'),
('6', 'Science', 'Curiosity – Class 6', 'Chapter 5 – Measurement of Length and Motion', 5, 'https://ncert.nic.in/textbook/pdf/fesc105.pdf'),
('6', 'Social Science', 'Exploring Society: India and Beyond – Class 6', 'Chapter 1 – Locating Places on the Earth', 1, 'https://ncert.nic.in/textbook/pdf/fess101.pdf'),
('6', 'Social Science', 'Exploring Society: India and Beyond – Class 6', 'Chapter 2 – Oceans and Continents', 2, 'https://ncert.nic.in/textbook/pdf/fess102.pdf'),
('6', 'Social Science', 'Exploring Society: India and Beyond – Class 6', 'Chapter 3 – Landforms and Life', 3, 'https://ncert.nic.in/textbook/pdf/fess103.pdf'),
('6', 'Social Science', 'Exploring Society: India and Beyond – Class 6', 'Chapter 4 – Timeline and Sources of History', 4, 'https://ncert.nic.in/textbook/pdf/fess104.pdf'),
('6', 'English', 'Poorvi – Class 6', 'Unit 1 – Fables and Folk Tales', 1, 'https://ncert.nic.in/textbook/pdf/feen101.pdf'),
('6', 'English', 'Poorvi – Class 6', 'Unit 2 – Friendship', 2, 'https://ncert.nic.in/textbook/pdf/feen102.pdf'),
('6', 'Hindi', 'Malhar – Class 6', 'पाठ 1 – मातृभूमि (कविता)', 1, 'https://ncert.nic.in/textbook/pdf/fhhn101.pdf'),
('6', 'Hindi', 'Malhar – Class 6', 'पाठ 2 – गोल', 2, 'https://ncert.nic.in/textbook/pdf/fhhn102.pdf'),

-- =================== CLASS 7 ===================
('7', 'Mathematics', 'Mathematics – Class 7', 'Chapter 1 – Integers', 1, 'https://ncert.nic.in/textbook/pdf/gemh101.pdf'),
('7', 'Mathematics', 'Mathematics – Class 7', 'Chapter 2 – Fractions and Decimals', 2, 'https://ncert.nic.in/textbook/pdf/gemh102.pdf'),
('7', 'Mathematics', 'Mathematics – Class 7', 'Chapter 3 – Data Handling', 3, 'https://ncert.nic.in/textbook/pdf/gemh103.pdf'),
('7', 'Mathematics', 'Mathematics – Class 7', 'Chapter 4 – Simple Equations', 4, 'https://ncert.nic.in/textbook/pdf/gemh104.pdf'),
('7', 'Mathematics', 'Mathematics – Class 7', 'Chapter 5 – Lines and Angles', 5, 'https://ncert.nic.in/textbook/pdf/gemh105.pdf'),
('7', 'Mathematics', 'Mathematics – Class 7', 'Chapter 6 – The Triangle and its Properties', 6, 'https://ncert.nic.in/textbook/pdf/gemh106.pdf'),
('7', 'Science', 'Science – Class 7', 'Chapter 1 – Nutrition in Plants', 1, 'https://ncert.nic.in/textbook/pdf/gesc101.pdf'),
('7', 'Science', 'Science – Class 7', 'Chapter 2 – Nutrition in Animals', 2, 'https://ncert.nic.in/textbook/pdf/gesc102.pdf'),
('7', 'Science', 'Science – Class 7', 'Chapter 3 – Heat', 3, 'https://ncert.nic.in/textbook/pdf/gesc103.pdf'),
('7', 'Science', 'Science – Class 7', 'Chapter 4 – Acids, Bases and Salts', 4, 'https://ncert.nic.in/textbook/pdf/gesc104.pdf'),
('7', 'Science', 'Science – Class 7', 'Chapter 5 – Physical and Chemical Changes', 5, 'https://ncert.nic.in/textbook/pdf/gesc105.pdf'),
('7', 'Science', 'Science – Class 7', 'Chapter 6 – Respiration in Organisms', 6, 'https://ncert.nic.in/textbook/pdf/gesc106.pdf'),
('7', 'Social Science', 'Our Pasts II – Class 7 (History)', 'Chapter 1 – Tracing Changes Through a Thousand Years', 1, 'https://ncert.nic.in/textbook/pdf/gess101.pdf'),
('7', 'Social Science', 'Our Pasts II – Class 7 (History)', 'Chapter 2 – Kings and Kingdoms', 2, 'https://ncert.nic.in/textbook/pdf/gess102.pdf'),
('7', 'Social Science', 'Our Environment – Class 7 (Geography)', 'Chapter 1 – Environment', 1, 'https://ncert.nic.in/textbook/pdf/gess201.pdf'),
('7', 'Social Science', 'Our Environment – Class 7 (Geography)', 'Chapter 2 – Inside Our Earth', 2, 'https://ncert.nic.in/textbook/pdf/gess202.pdf'),
('7', 'Social Science', 'Social and Political Life II – Class 7 (Civics)', 'Chapter 1 – On Equality', 1, 'https://ncert.nic.in/textbook/pdf/gess301.pdf'),
('7', 'English', 'Honeycomb – Class 7', 'Unit 1 – Three Questions', 1, 'https://ncert.nic.in/textbook/pdf/gehn101.pdf'),
('7', 'Hindi', 'Vasant Bhag 2 – Class 7', 'पाठ 1 – हम पंछी उन्मुक्त गगन के', 1, 'https://ncert.nic.in/textbook/pdf/ghvs101.pdf'),

-- =================== CLASS 8 ===================
('8', 'Mathematics', 'Mathematics – Class 8', 'Chapter 1 – Rational Numbers', 1, 'https://ncert.nic.in/textbook/pdf/hemh101.pdf'),
('8', 'Mathematics', 'Mathematics – Class 8', 'Chapter 2 – Linear Equations in One Variable', 2, 'https://ncert.nic.in/textbook/pdf/hemh102.pdf'),
('8', 'Mathematics', 'Mathematics – Class 8', 'Chapter 3 – Understanding Quadrilaterals', 3, 'https://ncert.nic.in/textbook/pdf/hemh103.pdf'),
('8', 'Mathematics', 'Mathematics – Class 8', 'Chapter 4 – Data Handling', 4, 'https://ncert.nic.in/textbook/pdf/hemh104.pdf'),
('8', 'Mathematics', 'Mathematics – Class 8', 'Chapter 5 – Squares and Square Roots', 5, 'https://ncert.nic.in/textbook/pdf/hemh105.pdf'),
('8', 'Mathematics', 'Mathematics – Class 8', 'Chapter 6 – Cubes and Cube Roots', 6, 'https://ncert.nic.in/textbook/pdf/hemh106.pdf'),
('8', 'Mathematics', 'Mathematics – Class 8', 'Chapter 7 – Comparing Quantities', 7, 'https://ncert.nic.in/textbook/pdf/hemh107.pdf'),
('8', 'Mathematics', 'Mathematics – Class 8', 'Chapter 8 – Algebraic Expressions and Identities', 8, 'https://ncert.nic.in/textbook/pdf/hemh108.pdf'),
('8', 'Mathematics', 'Mathematics – Class 8', 'Chapter 9 – Mensuration', 9, 'https://ncert.nic.in/textbook/pdf/hemh109.pdf'),
('8', 'Mathematics', 'Mathematics – Class 8', 'Chapter 10 – Exponents and Powers', 10, 'https://ncert.nic.in/textbook/pdf/hemh110.pdf'),
('8', 'Science', 'Science – Class 8', 'Chapter 1 – Crop Production and Management', 1, 'https://ncert.nic.in/textbook/pdf/hesc101.pdf'),
('8', 'Science', 'Science – Class 8', 'Chapter 2 – Microorganisms: Friend and Foe', 2, 'https://ncert.nic.in/textbook/pdf/hesc102.pdf'),
('8', 'Science', 'Science – Class 8', 'Chapter 3 – Coal and Petroleum', 3, 'https://ncert.nic.in/textbook/pdf/hesc103.pdf'),
('8', 'Science', 'Science – Class 8', 'Chapter 4 – Combustion and Flame', 4, 'https://ncert.nic.in/textbook/pdf/hesc104.pdf'),
('8', 'Science', 'Science – Class 8', 'Chapter 5 – Conservation of Plants and Animals', 5, 'https://ncert.nic.in/textbook/pdf/hesc105.pdf'),
('8', 'Science', 'Science – Class 8', 'Chapter 6 – Reproduction in Animals', 6, 'https://ncert.nic.in/textbook/pdf/hesc106.pdf'),
('8', 'Science', 'Science – Class 8', 'Chapter 7 – Reaching the Age of Adolescence', 7, 'https://ncert.nic.in/textbook/pdf/hesc107.pdf'),
('8', 'Science', 'Science – Class 8', 'Chapter 8 – Force and Pressure', 8, 'https://ncert.nic.in/textbook/pdf/hesc108.pdf'),
('8', 'Science', 'Science – Class 8', 'Chapter 9 – Friction', 9, 'https://ncert.nic.in/textbook/pdf/hesc109.pdf'),
('8', 'Science', 'Science – Class 8', 'Chapter 10 – Sound', 10, 'https://ncert.nic.in/textbook/pdf/hesc110.pdf'),
('8', 'Social Science', 'Our Pasts III – Class 8 (History)', 'Chapter 1 – How, When and Where', 1, 'https://ncert.nic.in/textbook/pdf/hess101.pdf'),
('8', 'Social Science', 'Resources and Development – Class 8 (Geography)', 'Chapter 1 – Resources', 1, 'https://ncert.nic.in/textbook/pdf/hess201.pdf'),
('8', 'Social Science', 'Social and Political Life III – Class 8 (Civics)', 'Chapter 1 – The Indian Constitution', 1, 'https://ncert.nic.in/textbook/pdf/hess301.pdf'),
('8', 'English', 'Honeydew – Class 8', 'Unit 1 – The Best Christmas Present in the World', 1, 'https://ncert.nic.in/textbook/pdf/hehd101.pdf'),
('8', 'Hindi', 'Vasant Bhag 3 – Class 8', 'पाठ 1 – लाख की चूड़ियाँ', 1, 'https://ncert.nic.in/textbook/pdf/hhvs101.pdf'),

-- =================== CLASS 9 ===================
('9', 'Mathematics', 'Mathematics – Class 9', 'Chapter 1 – Number Systems', 1, 'https://ncert.nic.in/textbook/pdf/iemh101.pdf'),
('9', 'Mathematics', 'Mathematics – Class 9', 'Chapter 2 – Polynomials', 2, 'https://ncert.nic.in/textbook/pdf/iemh102.pdf'),
('9', 'Mathematics', 'Mathematics – Class 9', 'Chapter 3 – Coordinate Geometry', 3, 'https://ncert.nic.in/textbook/pdf/iemh103.pdf'),
('9', 'Mathematics', 'Mathematics – Class 9', 'Chapter 4 – Linear Equations in Two Variables', 4, 'https://ncert.nic.in/textbook/pdf/iemh104.pdf'),
('9', 'Mathematics', 'Mathematics – Class 9', 'Chapter 5 – Introduction to Euclid Geometry', 5, 'https://ncert.nic.in/textbook/pdf/iemh105.pdf'),
('9', 'Mathematics', 'Mathematics – Class 9', 'Chapter 6 – Lines and Angles', 6, 'https://ncert.nic.in/textbook/pdf/iemh106.pdf'),
('9', 'Mathematics', 'Mathematics – Class 9', 'Chapter 7 – Triangles', 7, 'https://ncert.nic.in/textbook/pdf/iemh107.pdf'),
('9', 'Mathematics', 'Mathematics – Class 9', 'Chapter 8 – Quadrilaterals', 8, 'https://ncert.nic.in/textbook/pdf/iemh108.pdf'),
('9', 'Mathematics', 'Mathematics – Class 9', 'Chapter 9 – Circles', 9, 'https://ncert.nic.in/textbook/pdf/iemh109.pdf'),
('9', 'Mathematics', 'Mathematics – Class 9', 'Chapter 10 – Heron Formula', 10, 'https://ncert.nic.in/textbook/pdf/iemh110.pdf'),
('9', 'Mathematics', 'Mathematics – Class 9', 'Chapter 11 – Surface Areas and Volumes', 11, 'https://ncert.nic.in/textbook/pdf/iemh111.pdf'),
('9', 'Mathematics', 'Mathematics – Class 9', 'Chapter 12 – Statistics', 12, 'https://ncert.nic.in/textbook/pdf/iemh112.pdf'),
('9', 'Science', 'Science – Class 9', 'Chapter 1 – Matter in Our Surroundings', 1, 'https://ncert.nic.in/textbook/pdf/iesc101.pdf'),
('9', 'Science', 'Science – Class 9', 'Chapter 2 – Is Matter Around Us Pure', 2, 'https://ncert.nic.in/textbook/pdf/iesc102.pdf'),
('9', 'Science', 'Science – Class 9', 'Chapter 3 – Atoms and Molecules', 3, 'https://ncert.nic.in/textbook/pdf/iesc103.pdf'),
('9', 'Science', 'Science – Class 9', 'Chapter 4 – Structure of the Atom', 4, 'https://ncert.nic.in/textbook/pdf/iesc104.pdf'),
('9', 'Science', 'Science – Class 9', 'Chapter 5 – The Fundamental Unit of Life', 5, 'https://ncert.nic.in/textbook/pdf/iesc105.pdf'),
('9', 'Science', 'Science – Class 9', 'Chapter 6 – Tissues', 6, 'https://ncert.nic.in/textbook/pdf/iesc106.pdf'),
('9', 'Science', 'Science – Class 9', 'Chapter 7 – Motion', 7, 'https://ncert.nic.in/textbook/pdf/iesc107.pdf'),
('9', 'Science', 'Science – Class 9', 'Chapter 8 – Force and Laws of Motion', 8, 'https://ncert.nic.in/textbook/pdf/iesc108.pdf'),
('9', 'Science', 'Science – Class 9', 'Chapter 9 – Gravitation', 9, 'https://ncert.nic.in/textbook/pdf/iesc109.pdf'),
('9', 'Science', 'Science – Class 9', 'Chapter 10 – Work and Energy', 10, 'https://ncert.nic.in/textbook/pdf/iesc110.pdf'),
('9', 'Science', 'Science – Class 9', 'Chapter 11 – Sound', 11, 'https://ncert.nic.in/textbook/pdf/iesc111.pdf'),
('9', 'Science', 'Science – Class 9', 'Chapter 12 – Improvement in Food Resources', 12, 'https://ncert.nic.in/textbook/pdf/iesc112.pdf'),
('9', 'Social Science', 'India and Contemporary World I (History)', 'Chapter 1 – The French Revolution', 1, 'https://ncert.nic.in/textbook/pdf/iess101.pdf'),
('9', 'Social Science', 'Contemporary India I (Geography)', 'Chapter 1 – India – Size and Location', 1, 'https://ncert.nic.in/textbook/pdf/iess201.pdf'),
('9', 'Social Science', 'Democratic Politics I (Civics)', 'Chapter 1 – What is Democracy? Why Democracy?', 1, 'https://ncert.nic.in/textbook/pdf/iess401.pdf'),
('9', 'Social Science', 'Economics – Class 9', 'Chapter 1 – The Story of Village Palampur', 1, 'https://ncert.nic.in/textbook/pdf/iess301.pdf'),
('9', 'English', 'Beehive – Class 9', 'Chapter 1 – The Fun They Had', 1, 'https://ncert.nic.in/textbook/pdf/iebe101.pdf'),
('9', 'Hindi', 'Kshitij Bhag 1 – Class 9', 'पाठ 1 – दो बैलों की कथा', 1, 'https://ncert.nic.in/textbook/pdf/ihks101.pdf'),

-- =================== CLASS 10 ===================
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 1 – Real Numbers', 1, 'https://ncert.nic.in/textbook/pdf/jemh101.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 2 – Polynomials', 2, 'https://ncert.nic.in/textbook/pdf/jemh102.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 3 – Pair of Linear Equations in Two Variables', 3, 'https://ncert.nic.in/textbook/pdf/jemh103.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 4 – Quadratic Equations', 4, 'https://ncert.nic.in/textbook/pdf/jemh104.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 5 – Arithmetic Progressions', 5, 'https://ncert.nic.in/textbook/pdf/jemh105.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 6 – Triangles', 6, 'https://ncert.nic.in/textbook/pdf/jemh106.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 7 – Coordinate Geometry', 7, 'https://ncert.nic.in/textbook/pdf/jemh107.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 8 – Introduction to Trigonometry', 8, 'https://ncert.nic.in/textbook/pdf/jemh108.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 9 – Some Applications of Trigonometry', 9, 'https://ncert.nic.in/textbook/pdf/jemh109.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 10 – Circles', 10, 'https://ncert.nic.in/textbook/pdf/jemh110.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 11 – Areas Related to Circles', 11, 'https://ncert.nic.in/textbook/pdf/jemh111.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 12 – Surface Areas and Volumes', 12, 'https://ncert.nic.in/textbook/pdf/jemh112.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 13 – Statistics', 13, 'https://ncert.nic.in/textbook/pdf/jemh113.pdf'),
('10', 'Mathematics', 'Mathematics – Class 10', 'Chapter 14 – Probability', 14, 'https://ncert.nic.in/textbook/pdf/jemh114.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 1 – Chemical Reactions and Equations', 1, 'https://ncert.nic.in/textbook/pdf/jesc101.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 2 – Acids, Bases and Salts', 2, 'https://ncert.nic.in/textbook/pdf/jesc102.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 3 – Metals and Non-metals', 3, 'https://ncert.nic.in/textbook/pdf/jesc103.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 4 – Carbon and its Compounds', 4, 'https://ncert.nic.in/textbook/pdf/jesc104.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 5 – Life Processes', 5, 'https://ncert.nic.in/textbook/pdf/jesc105.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 6 – Control and Coordination', 6, 'https://ncert.nic.in/textbook/pdf/jesc106.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 7 – How do Organisms Reproduce', 7, 'https://ncert.nic.in/textbook/pdf/jesc107.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 8 – Heredity', 8, 'https://ncert.nic.in/textbook/pdf/jesc108.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 9 – Light – Reflection and Refraction', 9, 'https://ncert.nic.in/textbook/pdf/jesc109.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 10 – Human Eye and Colourful World', 10, 'https://ncert.nic.in/textbook/pdf/jesc110.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 11 – Electricity', 11, 'https://ncert.nic.in/textbook/pdf/jesc111.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 12 – Magnetic Effects of Electric Current', 12, 'https://ncert.nic.in/textbook/pdf/jesc112.pdf'),
('10', 'Science', 'Science – Class 10', 'Chapter 13 – Our Environment', 13, 'https://ncert.nic.in/textbook/pdf/jesc113.pdf'),
('10', 'Social Science', 'India and Contemporary World II (History)', 'Chapter 1 – The Rise of Nationalism in Europe', 1, 'https://ncert.nic.in/textbook/pdf/jess101.pdf'),
('10', 'Social Science', 'Contemporary India II (Geography)', 'Chapter 1 – Resources and Development', 1, 'https://ncert.nic.in/textbook/pdf/jess201.pdf'),
('10', 'Social Science', 'Democratic Politics II (Civics)', 'Chapter 1 – Power Sharing', 1, 'https://ncert.nic.in/textbook/pdf/jess401.pdf'),
('10', 'Social Science', 'Understanding Economic Development (Economics)', 'Chapter 1 – Development', 1, 'https://ncert.nic.in/textbook/pdf/jess301.pdf'),
('10', 'English', 'First Flight – Class 10', 'Chapter 1 – A Letter to God', 1, 'https://ncert.nic.in/textbook/pdf/jeff101.pdf'),
('10', 'Hindi', 'Kshitij Bhag 2 – Class 10', 'पाठ 1 – सूरदास के पद', 1, 'https://ncert.nic.in/textbook/pdf/jhks101.pdf'),

-- =================== CLASS 11 ===================
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 1 – Sets', 1, 'https://ncert.nic.in/textbook/pdf/kemh101.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 2 – Relations and Functions', 2, 'https://ncert.nic.in/textbook/pdf/kemh102.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 3 – Trigonometric Functions', 3, 'https://ncert.nic.in/textbook/pdf/kemh103.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 4 – Complex Numbers and Quadratic Equations', 4, 'https://ncert.nic.in/textbook/pdf/kemh104.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 5 – Linear Inequalities', 5, 'https://ncert.nic.in/textbook/pdf/kemh105.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 6 – Permutations and Combinations', 6, 'https://ncert.nic.in/textbook/pdf/kemh106.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 7 – Binomial Theorem', 7, 'https://ncert.nic.in/textbook/pdf/kemh107.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 8 – Sequences and Series', 8, 'https://ncert.nic.in/textbook/pdf/kemh108.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 9 – Straight Lines', 9, 'https://ncert.nic.in/textbook/pdf/kemh109.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 10 – Conic Sections', 10, 'https://ncert.nic.in/textbook/pdf/kemh110.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 11 – Introduction to Three Dimensional Geometry', 11, 'https://ncert.nic.in/textbook/pdf/kemh111.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 12 – Limits and Derivatives', 12, 'https://ncert.nic.in/textbook/pdf/kemh112.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 13 – Statistics', 13, 'https://ncert.nic.in/textbook/pdf/kemh113.pdf'),
('11', 'Mathematics', 'Mathematics – Class 11', 'Chapter 14 – Probability', 14, 'https://ncert.nic.in/textbook/pdf/kemh114.pdf'),
('11', 'Physics', 'Physics Part I – Class 11', 'Chapter 1 – Units and Measurements', 1, 'https://ncert.nic.in/textbook/pdf/keph101.pdf'),
('11', 'Physics', 'Physics Part I – Class 11', 'Chapter 2 – Motion in a Straight Line', 2, 'https://ncert.nic.in/textbook/pdf/keph102.pdf'),
('11', 'Physics', 'Physics Part I – Class 11', 'Chapter 3 – Motion in a Plane', 3, 'https://ncert.nic.in/textbook/pdf/keph103.pdf'),
('11', 'Physics', 'Physics Part I – Class 11', 'Chapter 4 – Laws of Motion', 4, 'https://ncert.nic.in/textbook/pdf/keph104.pdf'),
('11', 'Physics', 'Physics Part I – Class 11', 'Chapter 5 – Work, Energy and Power', 5, 'https://ncert.nic.in/textbook/pdf/keph105.pdf'),
('11', 'Physics', 'Physics Part I – Class 11', 'Chapter 6 – System of Particles and Rotational Motion', 6, 'https://ncert.nic.in/textbook/pdf/keph106.pdf'),
('11', 'Physics', 'Physics Part I – Class 11', 'Chapter 7 – Gravitation', 7, 'https://ncert.nic.in/textbook/pdf/keph107.pdf'),
('11', 'Physics', 'Physics Part II – Class 11', 'Chapter 8 – Mechanical Properties of Solids', 8, 'https://ncert.nic.in/textbook/pdf/keph201.pdf'),
('11', 'Physics', 'Physics Part II – Class 11', 'Chapter 9 – Mechanical Properties of Fluids', 9, 'https://ncert.nic.in/textbook/pdf/keph202.pdf'),
('11', 'Physics', 'Physics Part II – Class 11', 'Chapter 10 – Thermal Properties of Matter', 10, 'https://ncert.nic.in/textbook/pdf/keph203.pdf'),
('11', 'Physics', 'Physics Part II – Class 11', 'Chapter 11 – Thermodynamics', 11, 'https://ncert.nic.in/textbook/pdf/keph204.pdf'),
('11', 'Physics', 'Physics Part II – Class 11', 'Chapter 12 – Kinetic Theory', 12, 'https://ncert.nic.in/textbook/pdf/keph205.pdf'),
('11', 'Physics', 'Physics Part II – Class 11', 'Chapter 13 – Oscillations', 13, 'https://ncert.nic.in/textbook/pdf/keph206.pdf'),
('11', 'Physics', 'Physics Part II – Class 11', 'Chapter 14 – Waves', 14, 'https://ncert.nic.in/textbook/pdf/keph207.pdf'),
('11', 'Chemistry', 'Chemistry Part I – Class 11', 'Chapter 1 – Some Basic Concepts of Chemistry', 1, 'https://ncert.nic.in/textbook/pdf/kech101.pdf'),
('11', 'Chemistry', 'Chemistry Part I – Class 11', 'Chapter 2 – Structure of Atom', 2, 'https://ncert.nic.in/textbook/pdf/kech102.pdf'),
('11', 'Chemistry', 'Chemistry Part I – Class 11', 'Chapter 3 – Classification of Elements and Periodicity', 3, 'https://ncert.nic.in/textbook/pdf/kech103.pdf'),
('11', 'Chemistry', 'Chemistry Part I – Class 11', 'Chapter 4 – Chemical Bonding and Molecular Structure', 4, 'https://ncert.nic.in/textbook/pdf/kech104.pdf'),
('11', 'Chemistry', 'Chemistry Part I – Class 11', 'Chapter 5 – Chemical Thermodynamics', 5, 'https://ncert.nic.in/textbook/pdf/kech105.pdf'),
('11', 'Chemistry', 'Chemistry Part I – Class 11', 'Chapter 6 – Equilibrium', 6, 'https://ncert.nic.in/textbook/pdf/kech106.pdf'),
('11', 'Chemistry', 'Chemistry Part II – Class 11', 'Chapter 7 – Redox Reactions', 7, 'https://ncert.nic.in/textbook/pdf/kech201.pdf'),
('11', 'Chemistry', 'Chemistry Part II – Class 11', 'Chapter 8 – Organic Chemistry: Some Basic Principles', 8, 'https://ncert.nic.in/textbook/pdf/kech202.pdf'),
('11', 'Chemistry', 'Chemistry Part II – Class 11', 'Chapter 9 – Hydrocarbons', 9, 'https://ncert.nic.in/textbook/pdf/kech203.pdf'),
('11', 'Biology', 'Biology – Class 11', 'Chapter 1 – The Living World', 1, 'https://ncert.nic.in/textbook/pdf/kebo101.pdf'),
('11', 'Biology', 'Biology – Class 11', 'Chapter 2 – Biological Classification', 2, 'https://ncert.nic.in/textbook/pdf/kebo102.pdf'),
('11', 'Biology', 'Biology – Class 11', 'Chapter 3 – Plant Kingdom', 3, 'https://ncert.nic.in/textbook/pdf/kebo103.pdf'),
('11', 'Biology', 'Biology – Class 11', 'Chapter 4 – Animal Kingdom', 4, 'https://ncert.nic.in/textbook/pdf/kebo104.pdf'),
('11', 'Biology', 'Biology – Class 11', 'Chapter 8 – Cell: The Unit of Life', 8, 'https://ncert.nic.in/textbook/pdf/kebo108.pdf'),
('11', 'Computer Science', 'Computer Science – Class 11', 'Chapter 1 – Computer System', 1, 'https://ncert.nic.in/textbook/pdf/kecs101.pdf'),
('11', 'Computer Science', 'Computer Science – Class 11', 'Chapter 2 – Encoding Schemes and Number System', 2, 'https://ncert.nic.in/textbook/pdf/kecs102.pdf'),
('11', 'Computer Science', 'Computer Science – Class 11', 'Chapter 4 – Introduction to Problem Solving', 4, 'https://ncert.nic.in/textbook/pdf/kecs104.pdf'),
('11', 'Computer Science', 'Computer Science – Class 11', 'Chapter 5 – Getting Started with Python', 5, 'https://ncert.nic.in/textbook/pdf/kecs105.pdf'),

-- =================== CLASS 12 ===================
('12', 'Mathematics', 'Mathematics Part I – Class 12', 'Chapter 1 – Relations and Functions', 1, 'https://ncert.nic.in/textbook/pdf/lemh101.pdf'),
('12', 'Mathematics', 'Mathematics Part I – Class 12', 'Chapter 2 – Inverse Trigonometric Functions', 2, 'https://ncert.nic.in/textbook/pdf/lemh102.pdf'),
('12', 'Mathematics', 'Mathematics Part I – Class 12', 'Chapter 3 – Matrices', 3, 'https://ncert.nic.in/textbook/pdf/lemh103.pdf'),
('12', 'Mathematics', 'Mathematics Part I – Class 12', 'Chapter 4 – Determinants', 4, 'https://ncert.nic.in/textbook/pdf/lemh104.pdf'),
('12', 'Mathematics', 'Mathematics Part I – Class 12', 'Chapter 5 – Continuity and Differentiability', 5, 'https://ncert.nic.in/textbook/pdf/lemh105.pdf'),
('12', 'Mathematics', 'Mathematics Part I – Class 12', 'Chapter 6 – Application of Derivatives', 6, 'https://ncert.nic.in/textbook/pdf/lemh106.pdf'),
('12', 'Mathematics', 'Mathematics Part II – Class 12', 'Chapter 7 – Integrals', 7, 'https://ncert.nic.in/textbook/pdf/lemh201.pdf'),
('12', 'Mathematics', 'Mathematics Part II – Class 12', 'Chapter 8 – Application of Integrals', 8, 'https://ncert.nic.in/textbook/pdf/lemh202.pdf'),
('12', 'Mathematics', 'Mathematics Part II – Class 12', 'Chapter 9 – Differential Equations', 9, 'https://ncert.nic.in/textbook/pdf/lemh203.pdf'),
('12', 'Mathematics', 'Mathematics Part II – Class 12', 'Chapter 10 – Vector Algebra', 10, 'https://ncert.nic.in/textbook/pdf/lemh204.pdf'),
('12', 'Mathematics', 'Mathematics Part II – Class 12', 'Chapter 11 – Three Dimensional Geometry', 11, 'https://ncert.nic.in/textbook/pdf/lemh205.pdf'),
('12', 'Mathematics', 'Mathematics Part II – Class 12', 'Chapter 12 – Linear Programming', 12, 'https://ncert.nic.in/textbook/pdf/lemh206.pdf'),
('12', 'Mathematics', 'Mathematics Part II – Class 12', 'Chapter 13 – Probability', 13, 'https://ncert.nic.in/textbook/pdf/lemh207.pdf'),
('12', 'Physics', 'Physics Part I – Class 12', 'Chapter 1 – Electric Charges and Fields', 1, 'https://ncert.nic.in/textbook/pdf/leph101.pdf'),
('12', 'Physics', 'Physics Part I – Class 12', 'Chapter 2 – Electrostatic Potential and Capacitance', 2, 'https://ncert.nic.in/textbook/pdf/leph102.pdf'),
('12', 'Physics', 'Physics Part I – Class 12', 'Chapter 3 – Current Electricity', 3, 'https://ncert.nic.in/textbook/pdf/leph103.pdf'),
('12', 'Physics', 'Physics Part I – Class 12', 'Chapter 4 – Moving Charges and Magnetism', 4, 'https://ncert.nic.in/textbook/pdf/leph104.pdf'),
('12', 'Physics', 'Physics Part I – Class 12', 'Chapter 5 – Magnetism and Matter', 5, 'https://ncert.nic.in/textbook/pdf/leph105.pdf'),
('12', 'Physics', 'Physics Part I – Class 12', 'Chapter 6 – Electromagnetic Induction', 6, 'https://ncert.nic.in/textbook/pdf/leph106.pdf'),
('12', 'Physics', 'Physics Part I – Class 12', 'Chapter 7 – Alternating Current', 7, 'https://ncert.nic.in/textbook/pdf/leph107.pdf'),
('12', 'Physics', 'Physics Part I – Class 12', 'Chapter 8 – Electromagnetic Waves', 8, 'https://ncert.nic.in/textbook/pdf/leph108.pdf'),
('12', 'Physics', 'Physics Part II – Class 12', 'Chapter 9 – Ray Optics and Optical Instruments', 9, 'https://ncert.nic.in/textbook/pdf/leph201.pdf'),
('12', 'Physics', 'Physics Part II – Class 12', 'Chapter 10 – Wave Optics', 10, 'https://ncert.nic.in/textbook/pdf/leph202.pdf'),
('12', 'Physics', 'Physics Part II – Class 12', 'Chapter 11 – Dual Nature of Radiation and Matter', 11, 'https://ncert.nic.in/textbook/pdf/leph203.pdf'),
('12', 'Physics', 'Physics Part II – Class 12', 'Chapter 12 – Atoms', 12, 'https://ncert.nic.in/textbook/pdf/leph204.pdf'),
('12', 'Physics', 'Physics Part II – Class 12', 'Chapter 13 – Nuclei', 13, 'https://ncert.nic.in/textbook/pdf/leph205.pdf'),
('12', 'Physics', 'Physics Part II – Class 12', 'Chapter 14 – Semiconductor Electronics', 14, 'https://ncert.nic.in/textbook/pdf/leph206.pdf'),
('12', 'Chemistry', 'Chemistry Part I – Class 12', 'Chapter 1 – Solutions', 1, 'https://ncert.nic.in/textbook/pdf/lech101.pdf'),
('12', 'Chemistry', 'Chemistry Part I – Class 12', 'Chapter 2 – Electrochemistry', 2, 'https://ncert.nic.in/textbook/pdf/lech102.pdf'),
('12', 'Chemistry', 'Chemistry Part I – Class 12', 'Chapter 3 – Chemical Kinetics', 3, 'https://ncert.nic.in/textbook/pdf/lech103.pdf'),
('12', 'Chemistry', 'Chemistry Part I – Class 12', 'Chapter 4 – The d-and f-Block Elements', 4, 'https://ncert.nic.in/textbook/pdf/lech104.pdf'),
('12', 'Chemistry', 'Chemistry Part I – Class 12', 'Chapter 5 – Coordination Compounds', 5, 'https://ncert.nic.in/textbook/pdf/lech105.pdf'),
('12', 'Chemistry', 'Chemistry Part II – Class 12', 'Chapter 6 – Haloalkanes and Haloarenes', 6, 'https://ncert.nic.in/textbook/pdf/lech201.pdf'),
('12', 'Chemistry', 'Chemistry Part II – Class 12', 'Chapter 7 – Alcohols, Phenols and Ethers', 7, 'https://ncert.nic.in/textbook/pdf/lech202.pdf'),
('12', 'Chemistry', 'Chemistry Part II – Class 12', 'Chapter 8 – Aldehydes, Ketones and Carboxylic Acids', 8, 'https://ncert.nic.in/textbook/pdf/lech203.pdf'),
('12', 'Chemistry', 'Chemistry Part II – Class 12', 'Chapter 9 – Amines', 9, 'https://ncert.nic.in/textbook/pdf/lech204.pdf'),
('12', 'Chemistry', 'Chemistry Part II – Class 12', 'Chapter 10 – Biomolecules', 10, 'https://ncert.nic.in/textbook/pdf/lech205.pdf'),
('12', 'Biology', 'Biology – Class 12', 'Chapter 1 – Sexual Reproduction in Flowering Plants', 1, 'https://ncert.nic.in/textbook/pdf/lebo101.pdf'),
('12', 'Biology', 'Biology – Class 12', 'Chapter 2 – Human Reproduction', 2, 'https://ncert.nic.in/textbook/pdf/lebo102.pdf'),
('12', 'Biology', 'Biology – Class 12', 'Chapter 3 – Reproductive Health', 3, 'https://ncert.nic.in/textbook/pdf/lebo103.pdf'),
('12', 'Biology', 'Biology – Class 12', 'Chapter 4 – Principles of Inheritance and Variation', 4, 'https://ncert.nic.in/textbook/pdf/lebo104.pdf'),
('12', 'Biology', 'Biology – Class 12', 'Chapter 5 – Molecular Basis of Inheritance', 5, 'https://ncert.nic.in/textbook/pdf/lebo105.pdf'),
('12', 'Computer Science', 'Computer Science – Class 12', 'Chapter 1 – Python Revision Tour', 1, 'https://ncert.nic.in/textbook/pdf/lecs101.pdf'),
('12', 'Computer Science', 'Computer Science – Class 12', 'Chapter 2 – Python Revision Tour II', 2, 'https://ncert.nic.in/textbook/pdf/lecs102.pdf'),
('12', 'Computer Science', 'Computer Science – Class 12', 'Chapter 3 – Working with Functions', 3, 'https://ncert.nic.in/textbook/pdf/lecs103.pdf'),
('12', 'Computer Science', 'Computer Science – Class 12', 'Chapter 4 – Using Python Libraries', 4, 'https://ncert.nic.in/textbook/pdf/lecs104.pdf'),
('12', 'Computer Science', 'Computer Science – Class 12', 'Chapter 5 – File Handling', 5, 'https://ncert.nic.in/textbook/pdf/lecs105.pdf'),
('12', 'Computer Science', 'Computer Science – Class 12', 'Chapter 8 – Data Structures: Stack', 8, 'https://ncert.nic.in/textbook/pdf/lecs108.pdf'),
('12', 'Computer Science', 'Computer Science – Class 12', 'Chapter 11 – Relational Databases and SQL', 11, 'https://ncert.nic.in/textbook/pdf/lecs111.pdf')
ON CONFLICT (class_number, subject, book_name, chapter_number) DO UPDATE
SET chapter_title = EXCLUDED.chapter_title, file_url = EXCLUDED.file_url;
