// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egisnlkoihntyctzlckk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnaXNubGtvaWhudHljdHpsY2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMDc2MzUsImV4cCI6MjA2NTc4MzYzNX0.nq-tDuO28seB3tS4-sji84Xjl-ISh1l-60ItkNn1rw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);